export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  CSRF_INVALID: 'CSRF_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  DEVICE_REVOKED: 'DEVICE_REVOKED',
  SPACE_ACCESS_REVOKED: 'SPACE_ACCESS_REVOKED',
  REVISION_CONFLICT: 'REVISION_CONFLICT',
  RESOURCE_DELETED: 'RESOURCE_DELETED',
  OPERATION_ID_REUSED: 'OPERATION_ID_REUSED',
  RESYNC_REQUIRED: 'RESYNC_REQUIRED',
  CONTRACT_UNSUPPORTED: 'CONTRACT_UNSUPPORTED',
  RATE_LIMITED: 'RATE_LIMITED',
  TEMPORARILY_UNAVAILABLE: 'TEMPORARILY_UNAVAILABLE',
  SNAPSHOT_TOO_LARGE: 'SNAPSHOT_TOO_LARGE',
  ID_COLLISION: 'ID_COLLISION',
  INVITE_INVALID: 'INVITE_INVALID',
  RECOVERY_INVALID: 'RECOVERY_INVALID',
  AI_NOT_CONFIGURED: 'AI_NOT_CONFIGURED',
  AI_CONSENT_REQUIRED: 'AI_CONSENT_REQUIRED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  BLOB_CORRUPT: 'BLOB_CORRUPT',
  EMERGENCY_CLOSED: 'EMERGENCY_CLOSED',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/** Default Vietnamese message per code; callers may pass a more specific one. */
export const DEFAULT_ERROR_MESSAGE: Record<ErrorCode, string> = {
  VALIDATION_FAILED: 'Dữ liệu không hợp lệ.',
  AUTH_REQUIRED: 'Cần xác thực thiết bị trước khi tiếp tục.',
  SESSION_EXPIRED: 'Phiên đã hết hạn, vui lòng xác thực lại.',
  CSRF_INVALID: 'Yêu cầu không hợp lệ (CSRF).',
  FORBIDDEN: 'Bạn không có quyền thực hiện thao tác này.',
  NOT_FOUND: 'Không tìm thấy.',
  DEVICE_REVOKED: 'Thiết bị này đã bị thu hồi quyền truy cập.',
  SPACE_ACCESS_REVOKED: 'Bạn không còn quyền truy cập không gian này.',
  REVISION_CONFLICT: 'Bản ghi đã được thay đổi ở nơi khác.',
  RESOURCE_DELETED: 'Bản ghi đã bị xóa.',
  OPERATION_ID_REUSED: 'Mã thao tác đã được dùng cho nội dung khác.',
  RESYNC_REQUIRED: 'Cần đồng bộ lại toàn bộ dữ liệu.',
  CONTRACT_UNSUPPORTED: 'Phiên bản ứng dụng không còn được hỗ trợ.',
  RATE_LIMITED: 'Quá nhiều yêu cầu, vui lòng thử lại sau.',
  TEMPORARILY_UNAVAILABLE: 'Dịch vụ tạm thời không khả dụng.',
  SNAPSHOT_TOO_LARGE: 'Dữ liệu quá lớn để tải một lần.',
  ID_COLLISION: 'Mã định danh đã tồn tại.',
  INVITE_INVALID: 'Lời mời không hợp lệ hoặc đã hết hạn.',
  RECOVERY_INVALID: 'Mã khôi phục không đúng hoặc đã được dùng.',
  AI_NOT_CONFIGURED: 'Chưa cấu hình trợ lý.',
  AI_CONSENT_REQUIRED: 'Cần đồng ý sử dụng trợ lý trước.',
  PAYLOAD_TOO_LARGE: 'Dữ liệu gửi lên quá lớn.',
  BLOB_CORRUPT: 'Tệp lưu trên máy chủ bị hỏng nên không thể mở. Hãy tải lên lại từ thiết bị còn bản gốc.',
  EMERGENCY_CLOSED: 'SOS này đã kết thúc.',
  INTERNAL: 'Đã có lỗi xảy ra, vui lòng thử lại.',
};
