import { randomUUID, createHash } from 'node:crypto';
import request from 'supertest';
import { AccessService } from '../../src/modules/access/access.service';
import { EmailChannel, type EmailMessage } from '../../src/modules/delivery/channels/email.channel';
import { withTransaction } from '../../src/database/transaction';
import { createTestApp, type TestApp } from '../helpers/test-app';
import { truncateAll } from '../helpers/db';
import { registerDevice, type RegisteredDevice } from '../helpers/session';
import { seedVerifiedAccount } from '../helpers/verified-account';
import { createSharedSpace, insertMember } from '../helpers/spaces';
import { itemPayload, op, sendOps } from '../helpers/sync';
const mail: EmailMessage[] = [];
let mailFails = false;
const fakeMail = { writesFiles: false, send: async (message: EmailMessage) => { if (mailFails) throw new Error('SMTP failure'); mail.push(message); return {}; } };
const token = () => {
  const match = /token=([A-Za-z0-9_-]+)/.exec(mail.at(-1)!.text);
  if (!match) throw new Error('Missing test token'); return match[1];
};
describe('family sharing workflows (int)', () => {
  let t: TestApp, owner: RegisteredDevice;
  beforeAll(async () => { t = await createTestApp({ overrides: [{ token: EmailChannel, value: fakeMail }] }); });
  beforeEach(async () => { await truncateAll(t.ds); mail.length = 0; mailFails = false; fakeMail.writesFiles = false; owner = await registerDevice(t.app); });
  afterAll(async () => { await t.close(); });
  it('requires a verified email before bootstrapping a family and links with a one-use token', async () => {
    const space = { id: randomUUID(), kind: 'FAMILY', name: 'Nhà mình', time_zone: 'Asia/Ho_Chi_Minh',
      settings: { weekStartsOn: 1, dateFormat: 'dd/MM/yyyy', showIllustrations: true, showQuickReminders: true, showUpcomingBirthdays: true, weatherEnabled: false } };
    const start = () => owner.agent.post('/api/v1/spaces/bootstrap').set('X-CSRF-Token', owner.csrf).send({ space });
    expect((await start()).status).toBe(422);
    await owner.agent.post('/api/v1/auth/magic-link').set('X-CSRF-Token', owner.csrf).send({ email: 'owner@example.com' }).expect(202);
    expect(mail[0].text).toContain('/xac-thuc/#purpose=link&token=');
    const secret = token();
    await owner.agent.post('/api/v1/auth/magic-link/verify').set('X-CSRF-Token', owner.csrf).send({ token: secret }).expect(200);
    await owner.agent.post('/api/v1/auth/magic-link/verify').set('X-CSRF-Token', owner.csrf).send({ token: secret }).expect(422);
    expect((await start()).status).toBe(201);
  });
  it('logs a new device into the proven actor without merging identities, rejects replay and wrong actors', async () => {
    await seedVerifiedAccount(t.ds, owner.actorId, 'owner@example.com');
    const access = t.app.get(AccessService);
    await createSharedSpace(t.ds, access, { ...owner, sessionId: '', accountId: null });
    const newBrowser = request.agent(t.app.getHttpServer());
    await newBrowser.post('/api/v1/auth/login').send({ email: 'owner@example.com' }).expect(202);
    const secret = token();
    const preview = await newBrowser.post('/api/v1/auth/login/preview').send({ token: secret }).expect(200);
    expect(preview.body.actors).toEqual([expect.objectContaining({ actor_id: owner.actorId })]);
    await newBrowser.post('/api/v1/auth/login/verify').send({ token: secret, actor_id: randomUUID(), device_id: randomUUID() }).expect(422);
    const deviceId = randomUUID();
    await newBrowser.post('/api/v1/auth/login/verify').send({ token: secret, actor_id: owner.actorId, device_id: deviceId }).expect(200);
    const session = await newBrowser.get('/api/v1/session').expect(200);
    expect(session.body).toMatchObject({ actorId: owner.actorId, deviceId });
    await newBrowser.post('/api/v1/auth/login/verify').send({ token: secret, actor_id: owner.actorId, device_id: randomUUID() }).expect(422);
    const devices = await owner.agent.get('/api/v1/devices').expect(200);
    expect(devices.body.devices).toHaveLength(2);
    await owner.agent.post('/api/v1/devices/' + deviceId + '/revoke').set('X-CSRF-Token', owner.csrf).expect(200);
    await newBrowser.get('/api/v1/session').expect(401);
  });
  it('manages membership only as owner and cannot remove the last owner', async () => {
    const access = t.app.get(AccessService);
    const space = await createSharedSpace(t.ds, access, { ...owner, sessionId: '', accountId: null });
    const guest = await registerDevice(t.app);
    await withTransaction(t.ds, (em) => access.addMembership(em, space.spaceId, guest.actorId, space.roleIds.ADULT));
    const endpoint = '/api/v1/spaces/' + space.spaceId + '/memberships/';
    await guest.agent.post(endpoint + owner.actorId + '/remove').set('X-CSRF-Token', guest.csrf).expect(403);
    await owner.agent.post(endpoint + owner.actorId + '/remove').set('X-CSRF-Token', owner.csrf).expect(422);
    await owner.agent.post(endpoint + guest.actorId + '/role').set('X-CSRF-Token', owner.csrf).send({ role_id: space.roleIds.MEMBER }).expect(200);
    await owner.agent.post(endpoint + guest.actorId + '/remove').set('X-CSRF-Token', owner.csrf).expect(200);
    await guest.agent.get('/api/v1/spaces/' + space.spaceId + '/sync/snapshot').expect(403);
  });
  it('keeps the invitation usable and reports honest SMTP or file-mail delivery states', async () => {
    const access = t.app.get(AccessService);
    const space = await createSharedSpace(t.ds, access, { ...owner, sessionId: '', accountId: null });
    const create = () => owner.agent.post('/api/v1/spaces/' + space.spaceId + '/invites').set('X-CSRF-Token', owner.csrf)
      .send({ expires_in_hours: 48, max_uses: 1, approval_policy: 'APPROVAL_REQUIRED', proposed_role: 'MEMBER', email: 'guest@example.com' });
    expect((await create().expect(201)).body.email_delivery).toBe('SENT');
    mailFails = true;
    const failed = await create().expect(201);
    expect(failed.body.email_delivery).toBe('FAILED');
    await request(t.app.getHttpServer()).post('/api/v1/invites/preview').send({ token: failed.body.token }).expect(200);
    mailFails = false; fakeMail.writesFiles = true;
    expect((await create().expect(201)).body.email_delivery).toBe('NOT_CONFIGURED');
  });
  it('serves avatar bytes by member access and protects private audio even from another reference', async () => {
    const access = t.app.get(AccessService);
    const space = await createSharedSpace(t.ds, access, { ...owner, sessionId: '', accountId: null });
    const guest = await registerDevice(t.app);
    await withTransaction(t.ds, (em) => access.addMembership(em, space.spaceId, guest.actorId, space.roleIds.ADULT));
    const member = await insertMember(t.ds, space.spaceId, owner.actorId, 'PARENT');
    const avatar = randomUUID();
    await t.ds.query('UPDATE members SET avatar = ? WHERE id = ?', ['blob:' + avatar, member]);
    const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1sAAAAASUVORK5CYII=', 'base64');
    const root = '/api/v1/spaces/' + space.spaceId + '/media/';
    const avatarUrl = root + 'member/' + member + '/' + avatar;
    await owner.agent.post(avatarUrl).set('X-CSRF-Token', owner.csrf).set('Content-Type', 'image/png').set('X-Content-SHA256', createHash('sha256').update(png).digest('hex')).send(png).expect(201);
    const image = await guest.agent.get(avatarUrl).expect(200);
    expect(image.headers['cache-control']).toBe('private, no-store');
    expect(image.body).toEqual(png);
    await withTransaction(t.ds, (em) => access.assignRole(em, space.spaceId, guest.actorId, space.roleIds.MEMBER));
    await guest.agent.post(avatarUrl).set('X-CSRF-Token', guest.csrf).set('Content-Type', 'image/png').set('X-Content-SHA256', createHash('sha256').update(png).digest('hex')).send(png).expect(403);
    await withTransaction(t.ds, (em) => access.assignRole(em, space.spaceId, guest.actorId, space.roleIds.ADULT));
    const audio = randomUUID(), item = itemPayload(space.spaceId, owner.actorId, { audioAssetId: audio, sharingScope: 'PRIVATE' });
    const created = await sendOps(owner, space.spaceId, [op({ resource_type: 'item', resource_id: item.id, action: 'create', payload: item })]);
    expect(created.body.results[0].status).toBe('APPLIED');
    const audioUrl = root + 'item/' + item.id + '/' + audio;
    const bytes = Buffer.from('test recording');
    await owner.agent.post(audioUrl).set('X-CSRF-Token', owner.csrf).set('Content-Type', 'audio/webm').set('X-Content-SHA256', createHash('sha256').update(bytes).digest('hex')).send(bytes).expect(201);
    await guest.agent.get(audioUrl).expect(403);
    const copied = itemPayload(space.spaceId, guest.actorId, { audioAssetId: audio });
    const copyResult = await sendOps(guest, space.spaceId, [op({ resource_type: 'item', resource_id: copied.id, action: 'create', payload: copied })]);
    expect(copyResult.body.results[0].status).toBe('APPLIED');
    await guest.agent.get(root + 'item/' + copied.id + '/' + audio).expect(404);
    await t.ds.query("UPDATE members SET sharing_scope = 'PRIVATE' WHERE id = ?", [member]);
    await guest.agent.get(avatarUrl).expect(403);
  });
});
