// Crops illustrations from docs/UI-UX mockups (OWN-06); aliases cover screens whose mockup has no own artwork.
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";
import { generatePwaIcons } from "./generate-pwa-icons.mjs";

const root = path.resolve(import.meta.dirname, "..");
const uiDir = path.resolve(root, "../docs/UI-UX");
const outDir = path.join(root, "public/illustrations");
const map = JSON.parse(fs.readFileSync(path.join(import.meta.dirname, "crop-map.json"), "utf8"));
fs.mkdirSync(outDir, { recursive: true });

function circleMask(w, h) {
  const r = Math.min(w, h) / 2;
  return Buffer.from(`<svg width="${w}" height="${h}"><circle cx="${w / 2}" cy="${h / 2}" r="${r}" fill="#fff"/></svg>`);
}

// Paints over mockup lettering that bleeds into a crop (ui-ux.md: mask, never redraw).
function eraseOverlay(w, h, rects) {
  const shapes = rects.map(([x, y, rw, rh, fill]) => `<rect x="${x}" y="${y}" width="${rw}" height="${rh}" rx="6" fill="${fill}"/>`).join("");
  return Buffer.from(`<svg width="${w}" height="${h}">${shapes}</svg>`);
}

async function crop(name) {
  const a = map.assets[name];
  const [left, top, width, height] = a.rect;
  let img = sharp(path.join(uiDir, map.sources[a.src])).extract({ left, top, width, height });
  // Flattened to a buffer: sharp runs composite after resize, which would misplace the overlay on the @2x copy.
  if (a.erase) img = sharp(await sharp(await img.png().toBuffer()).composite([{ input: eraseOverlay(width, height, a.erase) }]).png().toBuffer());
  if (a.round) img = sharp(await img.png().toBuffer()).composite([{ input: circleMask(width, height), blend: "dest-in" }]);
  return img;
}

for (const name of Object.keys(map.assets)) {
  const img = await crop(name);
  await img.webp({ quality: 90 }).toFile(path.join(outDir, `${name}.webp`));
  // Upscaled @2x keeps edges smoother on HiDPI than browser scaling of the tiny crop.
  const { width, height } = await (await crop(name)).png().toBuffer({ resolveWithObject: true }).then((r) => r.info);
  await (await crop(name)).resize(width * 2, height * 2, { kernel: "lanczos3" }).webp({ quality: 88 }).toFile(path.join(outDir, `${name}@2x.webp`));
}
for (const [alias, target] of Object.entries(map.aliases)) {
  for (const suffix of ["", "@2x"]) fs.copyFileSync(path.join(outDir, `${target}${suffix}.webp`), path.join(outDir, `${alias}${suffix}.webp`));
}

// Generated aspect table lets components size images by height without CSS one-axis overrides.
const sizes = {};
for (const [name, a] of Object.entries(map.assets)) sizes[name] = [a.rect[2], a.rect[3]];
for (const [alias, target] of Object.entries(map.aliases)) sizes[alias] = sizes[target];
const sizeLines = Object.keys(sizes)
  .sort()
  .map((k) => `  "${k}": [${sizes[k][0]}, ${sizes[k][1]}],`);
fs.writeFileSync(
  path.join(root, "src/design/illustration-sizes.ts"),
  `// Generated by scripts/crop-assets.mjs from crop-map.json. Do not edit by hand.\nexport const ILLUSTRATION_SIZES = {\n${sizeLines.join("\n")}\n} as const;\n\nexport type IllustrationName = keyof typeof ILLUSTRATION_SIZES;\n`,
);

await generatePwaIcons();
console.log(`cropped ${Object.keys(map.assets).length} assets + ${Object.keys(map.aliases).length} aliases`);
