// Generated by scripts/gen-api-types.mjs from src/core/api/openapi.json — do not edit.
export interface paths {
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DevicesController_list"];
        put?: never;
        post: operations["DevicesController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DevicesController_revoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/{token}/join-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InvitesController_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/{token}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InvitesController_preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/join-requests/{rid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InvitesController_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/join-requests/{rid}/guardian-confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InvitesController_guardianConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/guardian-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InvitesController_guardianInbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SessionController_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SessionController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpacesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpacesController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}/bootstrap/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SpacesController_activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}/bootstrap/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SpacesController_chunk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InvitesController_list"];
        put?: never;
        post: operations["InvitesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}/invites/{iid}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InvitesController_revoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}/join-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InvitesController_listRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}/join-requests/{rid}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InvitesController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}/join-requests/{rid}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InvitesController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}/sync/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChangesController_changes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}/sync/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OperationsController_apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}/sync/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChangesController_snapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SpacesController_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivateSpaceDto: {
            /** @description Records uploaded per resource type (system roles excluded); omitted types count as 0. */
            expected_counts: {
                [key: string]: number;
            };
            /**
             * Format: uuid
             * @description The uploaded Member that is the creator (SELF link).
             */
            self_member_id?: string;
        };
        ActivateSpaceResponseDto: {
            /** @enum {string} */
            state: "SHARED";
            /** @description change_seq after activation; equals the snapshot watermark. */
            watermark: string;
        };
        ApproveJoinRequestDto: {
            /**
             * Format: uuid
             * @description Link to this existing Member (exclusive with new_member).
             */
            member_id?: string;
            /** @description Create a Member for the requester (exclusive with member_id). */
            new_member?: components["schemas"]["NewMemberDto"];
            role_key: string;
        };
        BootstrapChunkDto: {
            /**
             * Format: uuid
             * @description Client UUID; resending the same chunk is a no-op.
             */
            chunk_id: string;
            records: components["schemas"]["BootstrapRecordDto"][];
        };
        BootstrapChunkResponseDto: {
            accepted: number;
        };
        BootstrapRecordDto: {
            /** @description Same payload as a sync create. */
            payload: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            resource_id: string;
            /** @enum {string} */
            resource_type: "member" | "role" | "item" | "item_exception" | "occurrence_state" | "checklist_item" | "checklist_state" | "participation" | "reminder_rule" | "finance_account" | "finance_txn" | "finance_budget" | "finance_saving" | "finance_loan" | "finance_goal" | "health_profile" | "health_metric" | "health_note" | "folder" | "file" | "automation" | "template";
        };
        BootstrapSpaceDto: {
            space: components["schemas"]["BootstrapSpaceInputDto"];
        };
        BootstrapSpaceInputDto: {
            /**
             * Format: uuid
             * @description The local Space id; kept as the server id.
             */
            id: string;
            /** @enum {string} */
            kind: "FAMILY" | "GROUP";
            name: string;
            /** @description SpaceSettings (camelCase, frontend schema). */
            settings: {
                [key: string]: unknown;
            };
            /** @example Asia/Ho_Chi_Minh */
            time_zone: string;
        };
        BootstrapSpaceResponseDto: {
            /** Format: uuid */
            space_id: string;
            /** @enum {string} */
            state: "INITIALIZING" | "SHARED";
        };
        ChangeDto: {
            /** @enum {string} */
            op: "UPSERT" | "DELETE";
            /** @description UPSERT only: current record (camelCase, frontend schema) as the caller may see it. */
            record?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            resource_id: string;
            /** @enum {string} */
            resource_type: "space_settings" | "member" | "role" | "item" | "item_exception" | "occurrence_state" | "checklist_item" | "checklist_state" | "participation" | "reminder_rule" | "finance_account" | "finance_txn" | "finance_budget" | "finance_saving" | "finance_loan" | "finance_goal" | "health_profile" | "health_metric" | "health_note" | "folder" | "file" | "automation" | "template";
            /** @description UPSERT: revision of `record`; DELETE: revision of the delete. */
            revision: string;
            /** @description change_seq of the entry, as a string. */
            seq: string;
        };
        ChangesResponseDto: {
            /** @description Only entries the caller may read now, latest per record. */
            changes: components["schemas"]["ChangeDto"][];
            has_more: boolean;
            /** @description Pass as `cursor` next time; advances past hidden entries too. */
            next_cursor: string;
            /** @description Differs from the cached value: reload the snapshot and drop records missing from it. */
            policy_version: string;
        };
        CreateInviteDto: {
            /** @enum {string} */
            approval_policy: "APPROVAL_REQUIRED";
            /** @description Addressee; the invite then shows in their GET /me/invitations. */
            email?: string;
            expires_in_hours: number;
            max_uses: number;
            /** @description Role key suggested to the approver (not OWNER/ORGANIZER). */
            proposed_role?: string;
        };
        CreateInviteResponseDto: {
            expires_at: string;
            /** Format: uuid */
            invite_id: string;
            /** @description Shown once; only its hash is stored. */
            token: string;
            /** @example /tham-gia/?token=… */
            url: string;
        };
        CreateJoinRequestDto: {
            display_name: string;
            /**
             * Format: uuid
             * @description Existing Member the requester says they are.
             */
            member_id?: string;
            /** @enum {string} */
            proposed_profile?: "PARENT" | "SENIOR" | "CHILD";
        };
        DeviceDto: {
            /** Format: date-time */
            createdAt: string;
            /** @description True for the device making this request. */
            current: boolean;
            /** Format: uuid */
            id: string;
            label: string | null;
            /** Format: date-time */
            lastSeenAt: string | null;
            /** Format: date-time */
            revokedAt: string | null;
            /** @enum {string} */
            status: "ACTIVE" | "REVOKED";
        };
        DeviceListDto: {
            devices: components["schemas"]["DeviceDto"][];
        };
        GuardianRequestDto: {
            created_at: string;
            display_name: string;
            /** Format: uuid */
            request_id: string;
            /** @enum {string} */
            space_kind: "FAMILY" | "GROUP";
            space_name: string;
        };
        GuardianRequestListDto: {
            requests: components["schemas"]["GuardianRequestDto"][];
        };
        HealthDto: {
            /** @enum {string} */
            db: "ok";
            /** @enum {string} */
            status: "ok";
        };
        InviteListDto: {
            invites: components["schemas"]["InviteSummaryDto"][];
        };
        InvitePreviewDto: {
            expires_at: string;
            inviter_display_name: string;
            /** @enum {string} */
            space_kind: "FAMILY" | "GROUP";
            space_name: string;
        };
        InviteSummaryDto: {
            created_at: string;
            email: string | null;
            expires_at: string;
            /** Format: uuid */
            invite_id: string;
            max_uses: number;
            proposed_role: string | null;
            /** @enum {string} */
            status: "ACTIVE" | "EXPIRED" | "USED_UP" | "REVOKED";
            uses: number;
        };
        JoinRequestCreatedDto: {
            /** Format: uuid */
            request_id: string;
            /** @enum {string} */
            status: "PENDING" | "PENDING_GUARDIAN" | "APPROVED" | "REJECTED" | "EXPIRED";
        };
        JoinRequestDecisionDto: {
            /** Format: uuid */
            member_id?: string;
            /** Format: uuid */
            request_id: string;
            /** @enum {string} */
            status: "PENDING" | "APPROVED" | "REJECTED";
        };
        JoinRequestListDto: {
            requests: components["schemas"]["JoinRequestSummaryDto"][];
        };
        JoinRequestStatusDto: {
            /**
             * Format: uuid
             * @description Only once APPROVED.
             */
            space_id?: string;
            /** @enum {string} */
            status: "PENDING" | "PENDING_GUARDIAN" | "APPROVED" | "REJECTED" | "EXPIRED";
        };
        JoinRequestSummaryDto: {
            created_at: string;
            device_label: string | null;
            display_name: string;
            /** Format: uuid */
            invite_id: string;
            member_id: string | null;
            proposed_profile: string | null;
            proposed_role: string | null;
            /** Format: uuid */
            request_id: string;
            /** @enum {string} */
            status: "PENDING" | "PENDING_GUARDIAN" | "APPROVED" | "REJECTED" | "EXPIRED";
        };
        MembershipDto: {
            /** Format: uuid */
            actorId: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            roleId: string;
        };
        NewMemberDto: {
            display_name: string;
            /** @enum {string} */
            profile: "PARENT" | "SENIOR" | "CHILD";
            /** @enum {string} */
            relationship: "FATHER" | "MOTHER" | "SON" | "DAUGHTER" | "GRANDFATHER" | "GRANDMOTHER" | "GUARDIAN" | "OTHER";
        };
        OperationDto: {
            /** @enum {string} */
            action: "create" | "update" | "delete" | "occurrence_action";
            /** @description Server revision the edit started from; null on create. */
            base_revision: string | null;
            /** @description ISO instant of the user action; informational only. */
            client_created_at: string;
            /**
             * Format: uuid
             * @description Client UUID; unchanged across retries.
             */
            operation_id: string;
            /** @description Full record (camelCase, frontend schema) for create/update/occurrence_action; null for delete. */
            payload: {
                [key: string]: unknown;
            } | null;
            /** Format: uuid */
            resource_id: string;
            /** @enum {string} */
            resource_type: "space_settings" | "member" | "role" | "item" | "item_exception" | "occurrence_state" | "checklist_item" | "checklist_state" | "participation" | "reminder_rule" | "finance_account" | "finance_txn" | "finance_budget" | "finance_saving" | "finance_loan" | "finance_goal" | "health_profile" | "health_metric" | "health_note" | "folder" | "file" | "automation" | "template";
            /** @enum {number} */
            schema_version: 1;
        };
        OperationErrorDto: {
            code: string;
            fields?: {
                [key: string]: string;
            };
            message: string;
        };
        OperationResultDto: {
            /** @description REVISION_CONFLICT / FORBIDDEN: current server record if the caller may read it, else null. */
            current?: {
                [key: string]: unknown;
            } | null;
            error?: components["schemas"]["OperationErrorDto"];
            /** Format: uuid */
            operation_id: string;
            /** @description APPLIED: canonical record as the caller may see it (null after delete or when no longer readable). */
            record?: {
                [key: string]: unknown;
            } | null;
            /** @description APPLIED: new server revision. */
            revision?: string;
            /** @enum {string} */
            status: "APPLIED" | "REJECTED";
        };
        RegisterDeviceDto: {
            /**
             * Format: uuid
             * @description Actor id generated by the client; stable across mode upgrades.
             */
            actorId: string;
            /** Format: uuid */
            deviceId: string;
            label?: string;
        };
        RegisterDeviceResponseDto: {
            /** Format: uuid */
            actorId: string;
            /** Format: uuid */
            deviceId: string;
        };
        SessionDto: {
            /** Format: uuid */
            accountId: string | null;
            /** Format: uuid */
            actorId: string;
            /** @description Echo in the X-CSRF-Token header on every write request. */
            csrfToken: string;
            /** Format: uuid */
            deviceId: string;
        };
        SnapshotAccessDto: {
            /** Format: uuid */
            actorId: string;
            guardianOfMemberIds: string[];
            matrix: {
                [key: string]: "NONE" | "VIEW" | "EDIT";
            };
            representedMemberIds: string[];
            restrictions: {
                [key: string]: string;
            };
            roleKey: string;
        };
        SnapshotResponseDto: {
            access: components["schemas"]["SnapshotAccessDto"];
            /** @description ACTIVE memberships of the Space. */
            memberships: components["schemas"]["MembershipDto"][];
            policy_version: string;
            /** @description Every live record the caller may read, keyed by resource type (space_settings excluded). */
            records: {
                [key: string]: {
                    [key: string]: unknown;
                }[];
            };
            /** @description The space_settings record. */
            space: {
                [key: string]: unknown;
            };
            /** @description change_seq the snapshot reflects; pull changes from here. */
            watermark: string;
        };
        SpaceListDto: {
            spaces: components["schemas"]["SpaceSummaryDto"][];
        };
        SpaceSummaryDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "FAMILY" | "GROUP";
            name: string;
            policyVersion: string;
            roleKey: string;
            /** @enum {string} */
            sharingState: "INITIALIZING" | "SHARED";
            timeZone: string;
        };
        SyncOperationsRequestDto: {
            /** @description At most 50 operations and 512 KB per request. */
            operations: components["schemas"]["OperationDto"][];
        };
        SyncOperationsResponseDto: {
            policy_version: string;
            results: components["schemas"]["OperationResultDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    DevicesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListDto"];
                };
            };
        };
    };
    DevicesController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceDto"];
            };
        };
        responses: {
            /** @description Sets fc_sid (HttpOnly) and fc_csrf cookies. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterDeviceResponseDto"];
                };
            };
        };
    };
    DevicesController_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDto"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    InvitesController_join: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJoinRequestDto"];
            };
        };
        responses: {
            /** @description Idempotent per invite and Actor. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinRequestCreatedDto"];
                };
            };
        };
    };
    InvitesController_preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 404 INVITE_INVALID for unknown, revoked, expired or used-up invites. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreviewDto"];
                };
            };
        };
    };
    InvitesController_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Own requests only; 404 otherwise. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinRequestStatusDto"];
                };
            };
        };
    };
    InvitesController_guardianConfirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caller must be a Family guardian of the requester. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinRequestDecisionDto"];
                };
            };
        };
    };
    InvitesController_guardianInbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardianRequestListDto"];
                };
            };
        };
    };
    SessionController_current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    SessionController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SpacesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spaces with an ACTIVE membership; INITIALIZING ones only for their creator. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceListDto"];
                };
            };
        };
    };
    SpacesController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceSummaryDto"];
                };
            };
        };
    };
    SpacesController_activate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateSpaceDto"];
            };
        };
        responses: {
            /** @description 422 COUNT_MISMATCH per type keeps the Space INITIALIZING. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivateSpaceResponseDto"];
                };
            };
        };
    };
    SpacesController_chunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapChunkDto"];
            };
        };
        responses: {
            /** @description All-or-nothing per chunk. Errors carry fields.chunk_id + fields.index (+ records.<i>.<field>). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapChunkResponseDto"];
                };
            };
        };
    };
    InvitesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteListDto"];
                };
            };
        };
    };
    InvitesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteDto"];
            };
        };
        responses: {
            /** @description Needs members EDIT; 403 otherwise. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateInviteResponseDto"];
                };
            };
        };
    };
    InvitesController_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                iid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Waiting requests on this invite become REJECTED. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteSummaryDto"];
                };
            };
        };
    };
    InvitesController_listRequests: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinRequestListDto"];
                };
            };
        };
    };
    InvitesController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                rid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveJoinRequestDto"];
            };
        };
        responses: {
            /** @description 409 INVITE_INVALID when the invite expired, was revoked or is used up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinRequestDecisionDto"];
                };
            };
        };
    };
    InvitesController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinRequestDecisionDto"];
                };
            };
        };
    };
    ChangesController_changes: {
        parameters: {
            query?: {
                /** @description Last next_cursor (or snapshot watermark); default 0. */
                cursor?: string;
                /** @description 1-500, default 500. */
                limit?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 409 RESYNC_REQUIRED when the cursor is ahead of the Space or older than the offline horizon. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesResponseDto"];
                };
            };
        };
    };
    OperationsController_apply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncOperationsRequestDto"];
            };
        };
        responses: {
            /** @description One result per operation, in order. 413 PAYLOAD_TOO_LARGE above 50 operations or 512 KB; 401/403 when the session, device or membership no longer allows writing to the Space. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncOperationsResponseDto"];
                };
            };
        };
    };
    ChangesController_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 413 SNAPSHOT_TOO_LARGE above the record cap. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponseDto"];
                };
            };
        };
    };
    SpacesController_start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapSpaceDto"];
            };
        };
        responses: {
            /** @description Creates the Space INITIALIZING with default roles and the caller as owner; a retry by the creator answers the same. 409 ID_COLLISION when the id belongs to someone else. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapSpaceResponseDto"];
                };
            };
        };
    };
}
