import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsOptional, IsString, MaxLength } from 'class-validator';
import { IsClientId } from '../../../common/ids';

export class RegisterDeviceDto {
  @ApiProperty({ format: 'uuid', description: 'Actor id generated by the client; stable across mode upgrades.' })
  @IsClientId()
  actorId: string;

  @ApiProperty({ format: 'uuid' })
  @IsClientId()
  deviceId: string;

  @ApiPropertyOptional({ maxLength: 100 })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  label?: string;
}

export class RegisterDeviceResponseDto {
  @ApiProperty({ format: 'uuid' }) actorId: string;
  @ApiProperty({ format: 'uuid' }) deviceId: string;
}
